sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EU109c7THRY4K719937Nu0PwJvK39NyjpT8cjapTl+JNIwECGLvEkeGrjrMMFi2kl7FEucAnp7mVRTLclMqMCR5HfuMo+qvsOq8lncsj0GVZXK0rjrBaNGpqqeTdz7fUWXfyMOcp2TENPJHcj6Zh4JltcqRy37J0iuwqXb+OiOpv6Xg1tL7N5cmOihrSU8PqwPyQ5OYweyEn1NdrzW91BB+CQdI/78/gr7+Kvt+6/oxLg3Hv3nYY/U97ZVAVq1G5gCfHq51gDNTUInDFuW+G31+3Lcq9RfRF0pfSVv/F1YdT+2TckmbPZ6YA7j/qi9Me5Cb5o9Zo75UK+Z1BIUmx3AQX/lTuTkY+Fyca+SjAP5y+jftEv1HagFrZoYdVTAujKK8Jz94WpLXfNAwMYwbXH9rXMSSWbtJdTZ4M2JlaGq1Ptx/b8h7y22eNy7P+wJ/A3UZNWdb91ZIp+QV9ueNzdSq5ZEmc7enBGgBdoXWGUFZ0zyQO+Zvi5q0Tlg1Tgz9Zo+EgZlMed4K57KxHi5xlPMW4rKLl6K+LhlQFwXz7JoJ2Xar2gSZ31Fycp9lQW/lD2ZlDQS1VKWDA2VoLFqlgmf0YP8mX14eCchoFL5ZOU3uCIyiPEU49QMRT0v9C28Kx3fSwF6El5pBUHCnRSZ50o1VvbM5WSYOzaXG33qj85hk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/State-of-the-Union-Addresses_5036
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy